### ISSUE TITLE
Assassins Creed

### ISSUE THREAD

**Issue by gabreek** [GrapheneCt/ThreadOptimizer#2]
you can assign 4 cores to all tasks but not to TaskThread1, TaskThread2 and TaskThread3, are the main threads and if you assign more than one core per task the game not launches

**Comment by simonizer2409** [comment]
You also can't assign more cores to "NGSUpdateTrhead". Otherwise the game will crash at startup. I did some comparisons (running the game @544p). There is no advantage running it with Thread Optimizer - at least not in using more cores, didn't change thread priorities. The framerate will stay completely the same (20-25 fps). Bottleneck seems to be the GPU.

**Comment by GrapheneCt** [comment]
Some games are programmed in way that editing attributes of some threads may break them. That is true for affinity, and especially for priority.

In most of the Vita games, GPU is the bottleneck.
